services:
    exporttoolkit.event_listener:
        class: Elements\Bundle\ExportToolkitBundle\EventListener\ExportListener
#        lazy: true
        arguments:
            - "@exporttoolkit.exportservice"
        tags:
            - { name: kernel.event_subscriber }


    exporttoolkit.exportservice:
        class: Elements\Bundle\ExportToolkitBundle\ExportService